main.py
from flask import Flask
from routes.rotas import user
from database.users_database import db, User, init_db

app = Flask(__name__)

app.config['DATABASE'] = 'Users.db'

init_db(app)

with db:
    db.create_tables([User])

app.register_blueprint(user)

@app.before_request
def before_request():
    if db.is_closed():
        db.connect()

@app.teardown_request
def teardown_request(exception):
    if not db.is_closed():
        db.close()

app.run(debug=True)

routes/rotas.py
from flask import Blueprint, render_template, request, redirect, url_for
from database.users_database import User

user = Blueprint('user', __name__)

@user.route('/')
def login():
    return render_template('login.html')


@user.route('/acesso', methods=['GET','POST'])
def acesso_cliente():
    if request.method == 'POST':
        senha = request.form.get('password')
        email = request.form.get('email')
    if User.email == email and User.senha == senha:
        return redirect(url_for('user.conta', user_email=email))
    else:
        return redirect(url_for('user.login'))


@user.route('/<user_email>')
def conta(user_email):
    return render_template('index.html', user=User.get(User.email == user_email) )


@user.route('/criar')
def criar_conta():
    return render_template('criar_conta.html')

@user.route('/criando', methods=['POST'])
def salvar_dados():
    nomef = request.form.get('nome')
    emailf = request.form.get('email')
    senhaf = request.form.get('senha')
    enderecof = request.form.get('endereco')
    telefonef = request.form.get('telefone')

    User.create(nome=nomef, email=emailf, senha=senhaf, endereco=enderecof, telefone=telefonef)
    return redirect(url_for('user.login'))

templates/criar_conta.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Formulário de Criação de Conta</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='criar_conta.css') }}">
</head>
<body>
    <div class="form-container">
        <h1>Criar Conta</h1>
        <form action="/criando" method="post">
            <div class="form-group">
                <label for="email">Email:</label>
                <input type="email" id="email" name="email" placeholder="Digite seu email" required>
            </div>

            <div class="form-group">
                <label for="nome">Nome:</label>
                <input type="text" id="nome" name="nome" placeholder="Digite seu nome" required>
            </div>

            <div class="form-group">
                <label for="telefone">Telefone:</label>
                <input type="tel" id="telefone" name="telefone" placeholder="Digite seu telefone" required>
            </div>

            <div class="form-group">
                <label for="endereco">Endereço:</label>
                <input type="text" id="endereco" name="endereco" placeholder="Digite seu endereço" required>
            </div>

            <div class="form-group">
                <label for="senha">Senha:</label>
                <input type="password" id="senha" name="senha" placeholder="Digite sua senha" required>
            </div>

            <div class="form-button">
                <button type="submit">Criar Conta</button>
            </div>
        </form>
    </div>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Página de Login</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
</head>

<body>
    <div class="container">
        <div class="image-container">
            <img src="static/images/{{ user.img }}.jpg" alt="Imagem de Login">
        </div>
        <div class="user-data">
            <h2>Bem-vindo, {{ user.nome }}</h2>
            <p><strong>Email:</strong> {{ user.email }}</p>
            <p><strong>Telefone:</strong> {{ user.telefone }}</p>
            <p><strong>Endereço:</strong> {{ user.endereco }}</p>
            <button class="logout-button">Sair</button>
        </div>
    </div>
</body>

</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Página de Login</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='login.css') }}">
</head>

<body>
    <div class="container">
        <div class="login-box">
            <h1>Bem-vindo</h1>
            <p>Por favor, faça o login para continuar</p>
            <form action="/acesso" method="POST">
                <div class="input-group">
                    <label for="email">E-mail</label>
                    <input type="email" id="email" name="email" placeholder="Digite seu e-mail" required>
                </div>
                <div class="input-group">
                    <label for="password">Senha</label>
                    <input type="password" id="password" name="password" placeholder="Digite sua senha" required>
                </div>
                <button type="submit" class="btn">Entrar</button>
            </form>
            <div class="footer">
                <a href="#">Esqueceu sua senha?</a>
                <span>|</span>
                <a href="{{ url_for('user.criar_conta') }}">Criar uma conta</a>
            </div>
        </div>
    </div>
</body>

</html>